import { LibroType } from '@/types/bible';

// Estructura de datos con los libros del Antiguo Testamento
export const antiguoTestamento: LibroType[] = [
    { nombre: "Génesis", id: "Genesis", capitulos: 50 },
    { nombre: "Éxodo", id: "Exodus", capitulos: 40 },
    { nombre: "Levítico", id: "Leviticus", capitulos: 27 },
    { nombre: "Números", id: "Numbers", capitulos: 36 },
    { nombre: "Deuteronomio", id: "Deuteronomy", capitulos: 34 },
    { nombre: "Josué", id: "Joshua", capitulos: 24 },
    { nombre: "Jueces", id: "Judges", capitulos: 21 },
    { nombre: "Rut", id: "Ruth", capitulos: 4 },
    { nombre: "1 Samuel", id: "Samuel_1", capitulos: 31 },
    { nombre: "2 Samuel", id: "Samuel_2", capitulos: 24 },
    { nombre: "1 Reyes", id: "Kings_1", capitulos: 22 },
    { nombre: "2 Reyes", id: "Kings_2", capitulos: 25 },
    { nombre: "1 Crónicas", id: "Chronicles_1", capitulos: 29 },
    { nombre: "2 Crónicas", id: "Chronicles_2", capitulos: 36 },
    { nombre: "Esdras", id: "Ezra", capitulos: 10 },
    { nombre: "Nehemías", id: "Nehemiah", capitulos: 13 },
    { nombre: "Ester", id: "Esther", capitulos: 10 },
    { nombre: "Job", id: "Job", capitulos: 42 },
    { nombre: "Salmos", id: "Psalms", capitulos: 150 },
    { nombre: "Proverbios", id: "Proverbs", capitulos: 31 },
    { nombre: "Eclesiastés", id: "Ecclesiastes", capitulos: 12 },
    { nombre: "Cantares", id: "Song_of_Songs", capitulos: 8 },
    { nombre: "Isaías", id: "Isaiah", capitulos: 66 },
    { nombre: "Jeremías", id: "Jeremiah", capitulos: 52 },
    { nombre: "Lamentaciones", id: "Lamentations", capitulos: 5 },
    { nombre: "Ezequiel", id: "Ezekiel", capitulos: 48 },
    { nombre: "Daniel", id: "Daniel", capitulos: 12 },
    { nombre: "Oseas", id: "Hosea", capitulos: 14 },
    { nombre: "Joel", id: "Joel", capitulos: 3 },
    { nombre: "Amós", id: "Amos", capitulos: 9 },
    { nombre: "Abdías", id: "Obadiah", capitulos: 1 },
    { nombre: "Jonás", id: "Jonah", capitulos: 4 },
    { nombre: "Miqueas", id: "Micah", capitulos: 7 },
    { nombre: "Nahúm", id: "Nahum", capitulos: 3 },
    { nombre: "Habacuc", id: "Habakkuk", capitulos: 3 },
    { nombre: "Sofonías", id: "Zephaniah", capitulos: 3 },
    { nombre: "Hageo", id: "Haggai", capitulos: 2 },
    { nombre: "Zacarías", id: "Zechariah", capitulos: 14 },
    { nombre: "Malaquías", id: "Malachi", capitulos: 4 }
];
